apiVersion: v1
kind: Pod
metadata:
  name: mount-cm-as-vol-to-pod
  namespace: default
spec:
  containers:
  - image: nginx:1.7.9
    name: nginx-with-cm
    volumeMounts:
    - name: car-vol
      mountPath: /etc/cars
  volumes:
  - name: car-vol
    configMap: 
      name: fast-car
