apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol-1
spec:
  capacity: 
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/sfw
    server: 172.31.28.67
    readOnly: false
